export { deploymentUiSchema } from './resource/deployment';
export { serviceUiSchema } from './resource/service';
export { statefulsetUiSchema } from './resource/statefulset';
export { daemonsetUiSchema } from './resource/daemonset';
export { configmapUiSchema } from './resource/configmap';
export { jobUiSchema } from './resource/job';
export { secretUiSchema } from './resource/secret';
export { cronjobUiSchema } from './resource/cronjob';
export { ingressUiSchema } from './resource/ingress';
