import * as yaml from 'js-yaml';
import type { K8sNode } from '../types/reactFlow';

export interface HelmFile {
  path: string;
  content: string;
}

function getMetadataName(node: K8sNode): string {
  return String((node.data.resource?.metadata as any)?.name || node.type || 'resource');
}

function sanitizeKey(s: string): string {
  return s.replace(/-/g, '_').replace(/[^a-z0-9_]/gi, '_');
}

function parseImage(image: string): { repository: string; tag: string } {
  const lastColon = image.lastIndexOf(':');
  if (lastColon === -1) return { repository: image, tag: 'latest' };
  const tag = image.slice(lastColon + 1);
  if (tag.includes('/')) return { repository: image, tag: 'latest' };
  return { repository: image.slice(0, lastColon), tag };
}

function generateChartYaml(chartName: string): string {
  return yaml.dump(
    {
      apiVersion: 'v2',
      name: chartName,
      description: 'A Helm chart generated by Kubernetes YAML Builder',
      type: 'application',
      version: '0.1.0',
      appVersion: '1.0.0',
    },
    { indent: 2 }
  );
}

function generateHelpersTpl(chartName: string): string {
  return `{{/*
Expand the name of the chart.
*/}}
{{- define "${chartName}.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "${chartName}.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Chart reference for labels.
*/}}
{{- define "${chartName}.chartref" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "${chartName}.labels" -}}
helm.sh/chart: {{ include "${chartName}.chartref" . }}
{{ include "${chartName}.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "${chartName}.selectorLabels" -}}
app.kubernetes.io/name: {{ include "${chartName}.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
`;
}

function generateValuesYaml(nodes: K8sNode[]): string {
  const values: Record<string, any> = {
    nameOverride: '',
    fullnameOverride: '',
  };

  for (const node of nodes) {
    const resource = node.data.resource as any;
    const kind = String(resource?.kind || '').toLowerCase();
    const name = getMetadataName(node);
    const key = sanitizeKey(name);

    if (!values[kind]) values[kind] = {};

    switch (kind) {
      case 'deployment':
      case 'statefulset': {
        const spec = (resource?.spec || {}) as any;
        const containers = spec?.template?.spec?.containers || [];
        const c = containers[0] || {};
        const image = parseImage(c.image || 'nginx:latest');
        values[kind][key] = {
          replicaCount: spec.replicas ?? 1,
          image: { repository: image.repository, tag: image.tag, pullPolicy: c.imagePullPolicy || 'IfNotPresent' },
        };
        if (c.ports?.[0]?.containerPort) {
          values[kind][key].containerPort = c.ports[0].containerPort;
        }
        break;
      }
      case 'daemonset': {
        const spec = (resource?.spec || {}) as any;
        const containers = spec?.template?.spec?.containers || [];
        const c = containers[0] || {};
        const image = parseImage(c.image || 'nginx:latest');
        values[kind][key] = {
          image: { repository: image.repository, tag: image.tag, pullPolicy: c.imagePullPolicy || 'IfNotPresent' },
        };
        break;
      }
      case 'service': {
        const spec = (resource?.spec || {}) as any;
        values[kind][key] = {
          type: spec.type || 'ClusterIP',
          port: spec.ports?.[0]?.port ?? 80,
          targetPort: spec.ports?.[0]?.targetPort ?? 80,
        };
        break;
      }
      case 'configmap': {
        values[kind][key] = { data: resource?.data || {} };
        break;
      }
      case 'secret': {
        values[kind][key] = {
          type: resource?.type || 'Opaque',
          data: resource?.data || {},
        };
        break;
      }
      case 'ingress': {
        values[kind][key] = {
          enabled: true,
          className: (resource?.spec as any)?.ingressClassName || '',
        };
        break;
      }
      default: {
        const metadata = (resource?.metadata || {}) as any;
        values[kind][key] = {
          name: metadata.name || name,
          namespace: metadata.namespace || 'default',
        };
      }
    }
  }

  const kindsUsed = Object.keys(values).filter((k) => k !== 'nameOverride' && k !== 'fullnameOverride');
  const header = `# Values for: ${kindsUsed.join(', ')}\n# Generated by Kubernetes YAML Builder\n\n`;
  return header + yaml.dump(values, { indent: 2 });
}

function generateResourceTemplate(node: K8sNode, _chartName: string): string {
  const resource = node.data.resource as any;
  const kind = String(resource?.kind || '').toLowerCase();
  const name = getMetadataName(node);
  const key = sanitizeKey(name);
  const valuesRef = `${kind}.${key}`;

  let template = yaml.dump(resource, { indent: 2 });

  // Replace metadata.name (first `  name:` = metadata.name, metadata is always first object block)
  template = template.replace(/^(  name: )(.+)$/m, `$1{{ .Release.Name }}-$2`);

  // Replace metadata.namespace
  template = template.replace(/^(  namespace: )(.+)$/m, `$1{{ .Release.Namespace }}`);

  switch (kind) {
    case 'deployment':
    case 'statefulset': {
      template = template.replace(
        /^(  replicas: )(\d+)$/m,
        `$1{{ .Values.${valuesRef}.replicaCount }}`
      );
      template = template.replace(
        /^( +image: )([^\n]+)$/m,
        `$1"{{ .Values.${valuesRef}.image.repository }}:{{ .Values.${valuesRef}.image.tag }}"`
      );
      break;
    }
    case 'daemonset': {
      template = template.replace(
        /^( +image: )([^\n]+)$/m,
        `$1"{{ .Values.${valuesRef}.image.repository }}:{{ .Values.${valuesRef}.image.tag }}"`
      );
      break;
    }
    case 'service': {
      template = template.replace(
        /^(  type: )(.+)$/m,
        `$1{{ .Values.${valuesRef}.type }}`
      );
      break;
    }
  }

  return `# Helm template for ${resource.kind}/${name}\n# Generated by Kubernetes YAML Builder\n\n${template}`;
}

export function generateHelmChart(nodes: K8sNode[], chartName: string): HelmFile[] {
  if (nodes.length === 0) return [];

  const helmChartNode = nodes.find((n) => (n.data.resource as any)?.kind === 'HelmChart');
  const helmValuesNode = nodes.find((n) => (n.data.resource as any)?.kind === 'HelmValues');
  const resourceNodes = nodes.filter(
    (n) => (n.data.resource as any)?.kind !== 'HelmChart' && (n.data.resource as any)?.kind !== 'HelmValues'
  );

  const chartRes = helmChartNode ? (helmChartNode.data.resource as any) : null;
  const resolvedName = (chartRes?.name as string) || chartName;

  const chartYaml = chartRes
    ? yaml.dump(
        {
          apiVersion: chartRes.apiVersion || 'v2',
          name: chartRes.name || resolvedName,
          description: chartRes.description || '',
          type: chartRes.type || 'application',
          version: chartRes.version || '0.1.0',
          appVersion: chartRes.appVersion || '1.0.0',
        },
        { indent: 2 }
      )
    : generateChartYaml(resolvedName);

  const valuesContent = helmValuesNode
    ? ((helmValuesNode.data.resource as any)?.content as string) || ''
    : generateValuesYaml(resourceNodes);

  const files: HelmFile[] = [
    { path: 'Chart.yaml', content: chartYaml },
    { path: 'values.yaml', content: valuesContent },
    { path: 'templates/_helpers.tpl', content: generateHelpersTpl(resolvedName) },
  ];

  for (const node of resourceNodes) {
    const resource = node.data.resource as any;
    const kind = String(resource?.kind || node.type || 'resource').toLowerCase();
    const name = getMetadataName(node);
    const safeName = name.replace(/[^a-z0-9]/gi, '-').toLowerCase();

    files.push({
      path: `templates/${kind}-${safeName}.yaml`,
      content: generateResourceTemplate(node, resolvedName),
    });
  }

  return files;
}
